export const DEFAULT_FORM_INPUTS: Record<string, any> = {
  complainantName: '陳小明',
  complainantId: 'A123456789',
  complainantAddress: '臺北市中正區重慶南路一段122號',
  complainantPhone: '0912345678',
  accusedName: '李大同',
  accusedId: 'B234567890',
  accusedAddress: '新北市板橋區縣民大道二段7號',
  prosecutorOffice: '臺灣臺北地方檢察署',
  courtName: '臺灣臺北地方法院',
  incidentDate: new Date().toISOString().split('T')[0],
  incidentLocation: '臺北市中正區忠孝西路一段與公園路交叉口',
  incidentDetails: '',
  claimAmount: '500000',
  demandTerms: '請准予依法起訴判決如訴之聲明。',
  debtAmount: '1000000',
  repaymentDeadline: '113年12月31日',
  interestRate: '5',
  issueSummary: '',
  evidenceList: '',
  officialCategory: '0202',
};
