export const DEFAULT_FORM_INPUTS: Record<string, any> = {
  // Common personal info
  complainantName: '',
  complainantPhone: '',
  complainantAddress: '',
  accusedName: '',
  // Will
  testatorName: '',
  birthDate: '',
  idNo: '',
  realEstateAddress: '',
  realEstateBeneficiary: '',
  bankName: '',
  executorName: '',
  // Waiver
  deathDate: '',
  knowDate: '',
  deceasedAddress: '',
  petitionerName: '',
  petitionerPhone: '',
  petitionerAddress: '',
  // Divorce
  husbandName: '',
  husbandId: '',
  wifeName: '',
  wifeId: '',
  childName: '',
  custodyParent: '女方 林雅婷',
  childSupport: '',
  payDay: '5',
  // Guardianship & Assistance
  wardName: '',
  wardBirth: '',
  wardIdNo: '',
  relationship: '長子',
  cdrScore: '',
  supervisorName: '',
  principalName: '',
  principalId: '',
  guardianName: '',
  guardianId: '',
  // Debt & Note
  creditorName: '',
  debtorName: '',
  debtAmount: '',
  noteDate: '',
  noteDueDate: '',
  paymentPlace: '',
  interestRate: '6',
  days: 365,
  loanDate: '',
  dueDate: '',
  // Demand Letter
  senderName: '',
  senderAddress: '',
  recipientName: '',
  recipientAddress: '',
  amount: '600,000',
  monthlyRent: '',
  defaultMonths: '2',
  leaseAddress: '',
  startDefaultMonth: '113年1月',
  hireDate: '',
  salary: '48,000',
  severancePay: '120,000',
  violationPeriod: '112年10月起迄今',
  // Execution
  employerName: '',
  employerAddress: '',
  titleCaseNo: '112年度司促字第12345號支付命令及確定證明書',
  claimAmount: '',
  // Real estate lease
  landlordName: '',
  landlordId: '',
  tenantName: '',
  tenantId: '',
  rentalAddress: '',
  depositAmount: '',
  startDate: '',
  endDate: '',
  // Spousal right & DV & Sexual assault
  plaintiffName: '',
  plaintiffAddress: '',
  plaintiffPhone: '',
  defendant1Name: '',
  defendant2Name: '',
  marriageDate: '',
  infringementStart: '112年9月間',
  injuryDetails: '身體擦挫傷、心理創傷與急性壓力障礙',
  evidenceList: '',
  requestedRelief: '命相對人遠離住居所與工作地100公尺、禁止騷擾與通訊'
};
