import { LegalCalculatorConfig } from '../../types/legalTools';
import { CHILD_SUPPORT_CALCULATOR_CONFIG } from './childSupport';
import { COURT_FEE_CALCULATOR_CONFIG } from './courtFee';
import { INHERITANCE_PORTION_CALCULATOR_CONFIG } from './inheritancePortion';
import { RESIDUAL_PROPERTY_CALCULATOR_CONFIG } from './residualProperty';
import { TRAFFIC_COMPENSATION_CALCULATOR_CONFIG } from './trafficCompensation';
import { SEVERANCE_PAY_CALCULATOR_CONFIG } from './severancePay';
import { STATUTE_LIMITATIONS_CALCULATOR_CONFIG } from './statuteLimitations';
import { CHILD_CUSTODY_ASSESSMENT_CONFIG } from './childCustody';

export const CALCULATOR_CONFIGS: Record<string, LegalCalculatorConfig> = {
  CHILD_SUPPORT_CALCULATOR: CHILD_SUPPORT_CALCULATOR_CONFIG,
  COURT_FEE_CALCULATOR: COURT_FEE_CALCULATOR_CONFIG,
  INHERITANCE_PORTION_CALCULATOR: INHERITANCE_PORTION_CALCULATOR_CONFIG,
  RESIDUAL_PROPERTY_CALCULATOR: RESIDUAL_PROPERTY_CALCULATOR_CONFIG,
  TRAFFIC_COMPENSATION_CALCULATOR: TRAFFIC_COMPENSATION_CALCULATOR_CONFIG,
  SEVERANCE_PAY_CALCULATOR: SEVERANCE_PAY_CALCULATOR_CONFIG,
  STATUTE_LIMITATIONS_CALCULATOR: STATUTE_LIMITATIONS_CALCULATOR_CONFIG,
  CHILD_CUSTODY_ASSESSMENT: CHILD_CUSTODY_ASSESSMENT_CONFIG
};

export function getCalculatorConfig(toolId: string): LegalCalculatorConfig | undefined {
  return CALCULATOR_CONFIGS[toolId];
}
